server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false  # Config Server kendi kendisini kullanmasın
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
